const actionTypes = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    RESET: 'RESET',
    TIME_ASYNC: 'TIME_ASYNC',
    TIME: 'TIME',
    SET_TITLE: 'SET_TITLE',
    SET_USER: 'SET_USER',
    START_INFINITY: 'START_INFINITY',
    STOP_INFINITY: 'STOP_INFINITY',

    LOGOUT_OK: 'LOGOUT_OK',
    LOGIN_OK: 'LOGIN_OK',
    LOGIN: 'LOGIN',
};

export default actionTypes;
