const actionTypes = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    RESET: 'RESET',
    TIME_ASYNC: 'TIME_ASYNC',
    TIME: 'TIME',
    SET_TITLE: 'SET_TITLE',
    SET_USER: 'SET_USER',
    START_INFINITY: 'START_INFINITY',
    STOP_INFINITY: 'STOP_INFINITY',
};

export default actionTypes;
